"""new socials

Revision ID: e221f518eebf
Revises: a609fd3f4c05
Create Date: 2025-09-09 13:36:14.360906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e221f518eebf'
down_revision = 'a609fd3f4c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_image_url')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('whatsapp_url')
        batch_op.drop_column('instagram_url')

    # ### end Alembic commands ###
